// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaRopa.Data.Context;

#nullable disable

namespace TiendaRopa.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120082726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaRopa.Modelos.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.FacturaCompras", b =>
                {
                    b.Property<int>("IdFacturaCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacturaCompras"));

                    b.Property<int?>("FacturaIdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdRopa")
                        .HasColumnType("int");

                    b.HasKey("IdFacturaCompras");

                    b.HasIndex("FacturaIdFactura");

                    b.HasIndex("IdRopa");

                    b.ToTable("FacturaCompras");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.Ropa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<byte>("Stock")
                        .HasColumnType("tinyint");

                    b.Property<string>("Tela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlRopa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ropa");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.Factura", b =>
                {
                    b.HasOne("TiendaRopa.Modelos.Usuario", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.FacturaCompras", b =>
                {
                    b.HasOne("TiendaRopa.Modelos.Factura", null)
                        .WithMany("Compras")
                        .HasForeignKey("FacturaIdFactura");

                    b.HasOne("TiendaRopa.Modelos.Ropa", "Ropa")
                        .WithMany()
                        .HasForeignKey("IdRopa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ropa");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.Factura", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("TiendaRopa.Modelos.Usuario", b =>
                {
                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
